services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=bank
        healthcheck:
            test: ["CMD-SHELL", "psql -U postgres"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
    api:
        build:
            context: .
        ports:
            - 8080:8080
        environment:
            - DB_SOURCE=postgresql://postgres:postgres@db:5432/bank?sslmode=disable
        depends_on:
            db:
                condition: service_healthy
                restart: true
