services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=bank
        healthcheck:
            test: ["CMD-SHELL", "psql -U postgres"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        ports:
            - 5432:5432
    redis:
        image: redis:7-alpine
        ports:
            - 6379:6379
    api:
        build:
            context: .
        ports:
            - 8080:8080
            - 8081:8081
        environment:
            - DB_SOURCE=postgresql://postgres:postgres@db:5432/bank?sslmode=disable
            - REDIS_ADDRESS=redis:6379
        depends_on:
            db:
                condition: service_healthy
                restart: true
            redis:
                condition: service_started
                restart: true
